name: Run kore-alerts every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # כל 10 דקות
  workflow_dispatch:        # מאפשר הרצה ידנית מה-GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run alert script
        run: node index.js
