name: Run kore-alerts every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # כל 5 דקות
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node index.js

    - name: Commit updated history
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add history.json
        git commit -m "🕒 Update sent history [bot]" || echo "No changes"
        git push || echo "No changes to push"
